farmdata2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('farmdb.urls',namespace='farmdb')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmdb/urls.py
from django.conf.urls import url, include
from . import views



app_name = 'farmdb'

urlpatterns = [
    url(r'^login/', views.login_user, name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^logout', views.logout_user, name='logout'),

    # CreateViews
    url(r'^create/AnimalGroup$', views.AnimalGroupCreateView.as_view(), name="AnimalGroupCreate"),
    url(r'^create/Breed$', views.BreedCreateView.as_view(), name="BreedCreate"),
    url(r'^create/AnimalSubGroup$', views.AnimalSubGroupCreateView.as_view(), name="AnimalSubGroupCreate"),
    url(r'^create/Origin$', views.OriginCreateView.as_view(), name="OriginCreate"),
    url(r'^create/Animal$', views.AnimalCreateView.as_view(), name="AnimalCreate"),
    url(r'^create/Reason$', views.ReasonCreateView.as_view(), name="ReasonCreate"),
    url(r'^create/Vet$', views.VetCreateView.as_view(), name="VetCreate"),
    url(r'^create/Medication$', views.MedicationCreateView.as_view(), name="MedicationCreate"),
    url(r'^create/MedsGiven$', views.MedsGivenCreateView.as_view(), name="MedsGivenCreate"),
    url(r'^create/EggLog$', views.EggLogCreateView.as_view(), name="EggLogCreate"),
    url(r'^create/Wormer$', views.WormerCreateView.as_view(), name="WormerCreate"),
    url(r'^create/SheepCare$', views.SheepCareCreateView.as_view(), name="SheepCareCreate"),
    url(r'^create/Forage$', views.ForageCreateView.as_view(), name="ForageCreate"),
    url(r'^create/Paddock$', views.PaddockCreateView.as_view(), name="PaddockCreate"),
    url(r'^create/Note$', views.NoteCreateView.as_view(), name="NoteCreate"),
    url(r'^create/Sale$', views.SaleCreateView.as_view(), name="SaleCreate"),
    url(r'^create/SlayHouse$', views.SlayHouseCreateView.as_view(), name="SlayHouseCreate"),
    url(r'^create/Slaughter$', views.SlaughterCreateView.as_view(), name="SlaughterCreate"),
    url(r'^create/OtherDest$', views.OtherDestCreateView.as_view(), name="OtherDestCreate"),
    url(r'^create/OtherReason$', views.OtherReasonCreateView.as_view(), name="OtherReasonCreate"),
    url(r'^create/OtherRemove$', views.OtherRemoveCreateView.as_view(), name="OtherRemoveCreate"),
    url(r'^create/FeedType$', views.FeedTypeCreateView.as_view(), name="FeedTypeCreate"),
    url(r'^create/FeedUnit$', views.FeedUnitCreateView.as_view(), name="FeedUnitCreate"),
    url(r'^create/FeedSubtype$', views.FeedSubtypeCreateView.as_view(), name="FeedSubtypeCreate"),
    url(r'^create/Vendor$', views.VendorCreateView.as_view(), name="VendorCreate"),
    url(r'^create/Destination$', views.DestinationCreateView.as_view(), name="DestinationCreate"),
    url(r'^create/FeedPurchase$', views.FeedPurchaseCreateView.as_view(), name="FeedPurchaseCreate"),

    # List views
    url(r'^list/Animal$', views.AnimalListView.as_view(), name='AnimalList'),
    url(r'^list/Reason$', views.ReasonListView.as_view(), name='ReasonList'),
    url(r'^list/AnimalGroup$', views.AnimalGroupListView.as_view(), name='AnimalGroupList'),
    url(r'^list/Breed$', views.BreedListView.as_view(), name='BreedList'),
    url(r'^list/AnimalSubGroup$', views.AnimalSubGroupListView.as_view(), name='AnimalSubGroupList'),
    url(r'^list/Origin$', views.OriginListView.as_view(), name='OriginList'),
    url(r'^list/Animal$', views.AnimalListView.as_view(), name='AnimalList'),
    url(r'^list/Reason$', views.ReasonListView.as_view(), name='ReasonList'),
    url(r'^list/Vet$', views.VetListView.as_view(), name='VetList'),
    url(r'^list/Medication$', views.MedicationListView.as_view(), name='MedicationList'),
    url(r'^list/MedsGiven$', views.MedsGivenListView.as_view(), name='MedsGivenList'),
    url(r'^list/EggLog$', views.EggLogListView.as_view(), name='EggLogList'),
    url(r'^list/Wormer$', views.WormerListView.as_view(), name='WormerList'),
    url(r'^list/SheepCare$', views.SheepCareListView.as_view(), name='SheepCareList'),
    url(r'^list/Forage$', views.ForageListView.as_view(), name='ForageList'),
    url(r'^list/Paddock$', views.PaddockListView.as_view(), name='PaddockList'),
    url(r'^list/Note$', views.NoteListView.as_view(), name='NoteList'),
    url(r'^list/Sale$', views.SaleListView.as_view(), name='SaleList'),
    url(r'^list/SlayHouse$', views.SlayHouseListView.as_view(), name='SlayHouseList'),
    url(r'^list/Slaughter$', views.SlaughterListView.as_view(), name='SlaughterList'),
    url(r'^list/OtherDest$', views.OtherDestListView.as_view(), name='OtherDestList'),
    url(r'^list/OtherReason$', views.OtherReasonListView.as_view(), name='OtherReasonList'),
    url(r'^list/OtherRemove$', views.OtherRemoveListView.as_view(), name='OtherRemoveList'),
    url(r'^list/FeedType$', views.FeedTypeListView.as_view(), name='FeedTypeList'),
    url(r'^list/FeedUnit$', views.FeedUnitListView.as_view(), name='FeedUnitList'),
    url(r'^list/FeedSubtype$', views.FeedSubtypeListView.as_view(), name='FeedSubtypeList'),
    url(r'^list/Vendor$', views.VendorListView.as_view(), name='VendorList'),
    url(r'^list/FeedPurchase$', views.FeedPurchaseListView.as_view(), name='FeedPurchaseList'),
    url(r'^list/Destination$', views.DestinationListView.as_view(), name='DestinationList'),

    # DetailViews

    # UpdateViews
    url(r'^update/AnimalGroup/(?P<pk>\d+)/$', views.AnimalGroupUpdateView.as_view(), name='AnimalGroupUpdate'),
    url(r'^update/Breed/(?P<pk>\d+)/$', views.BreedUpdateView.as_view(), name='BreedUpdate'),
    url(r'^update/AnimalSubGroup/(?P<pk>\d+)/$', views.AnimalSubGroupUpdateView.as_view(), name='AnimalSubGroupUpdate'),
    url(r'^update/Origin/(?P<pk>\d+)/$', views.OriginUpdateView.as_view(), name='OriginUpdate'),
    url(r'^update/Animal/(?P<pk>\d+)/$', views.AnimalUpdateView.as_view(), name='AnimalUpdate'),
    url(r'^update/Reason/(?P<pk>\d+)/$', views.ReasonUpdateView.as_view(), name='ReasonUpdate'),
    url(r'^update/Vet/(?P<pk>\d+)/$', views.VetUpdateView.as_view(), name='VetUpdate'),
    url(r'^update/Medication/(?P<pk>\d+)/$', views.MedicationUpdateView.as_view(), name='MedicationUpdate'),
    url(r'^update/MedsGiven/(?P<pk>\d+)/$', views.MedsGivenUpdateView.as_view(), name='MedsGivenUpdate'),
    url(r'^update/EggLog/(?P<pk>\d+)/$', views.EggLogUpdateView.as_view(), name='EggLogUpdate'),
    url(r'^update/Wormer/(?P<pk>\d+)/$', views.WormerUpdateView.as_view(), name='WormerUpdate'),
    url(r'^update/SheepCare/(?P<pk>\d+)/$', views.SheepCareUpdateView.as_view(), name='SheepCareUpdate'),
    url(r'^update/Forage/(?P<pk>\d+)/$', views.ForageUpdateView.as_view(), name='ForageUpdate'),
    url(r'^update/Paddock/(?P<pk>\d+)/$', views.PaddockUpdateView.as_view(), name='PaddockUpdate'),
    url(r'^update/Note/(?P<pk>\d+)/$', views.NoteUpdateView.as_view(), name='NoteUpdate'),
    url(r'^update/Destination/(?P<pk>\d+)/$', views.DestinationUpdateView.as_view(), name='DestinationUpdate'),
    url(r'^update/Sale/(?P<pk>\d+)/$', views.SaleUpdateView.as_view(), name='SaleUpdate'),
    url(r'^update/SlayHouse/(?P<pk>\d+)/$', views.SlayHouseUpdateView.as_view(), name='SlayHouseUpdate'),
    url(r'^update/Slaughter/(?P<pk>\d+)/$', views.SlaughterUpdateView.as_view(), name='SlaughterUpdate'),
    url(r'^update/OtherDest/(?P<pk>\d+)/$', views.OtherDestUpdateView.as_view(), name='OtherDestUpdate'),
    url(r'^update/OtherReason/(?P<pk>\d+)/$', views.OtherReasonUpdateView.as_view(), name='OtherReasonUpdate'),
    url(r'^update/OtherRemove/(?P<pk>\d+)/$', views.OtherRemoveUpdateView.as_view(), name='OtherRemoveUpdate'),
    url(r'^update/FeedType/(?P<pk>\d+)/$', views.FeedTypeUpdateView.as_view(), name='FeedTypeUpdate'),
    url(r'^update/FeedSubtype/(?P<pk>\d+)/$', views.FeedSubtypeUpdateView.as_view(), name='FeedSubtypeUpdate'),
    url(r'^update/FeedUnit/(?P<pk>\d+)/$', views.FeedUnitUpdateView.as_view(), name='FeedUnitUpdate'),
    url(r'^update/Vendor/(?P<pk>\d+)/$', views.VendorUpdateView.as_view(), name='VendorUpdate'),
    url(r'^update/FeedPurchase/(?P<pk>\d+)/$', views.FeedPurchaseUpdateView.as_view(), name='FeedPurchaseUpdate'),

    # DeleteViews
    url(r'^delete/AnimalGroup/(?P<pk>\d+)/$', views.AnimalGroupDelete.as_view(), name='AnimalGroupDelete'),
    url(r'^delete/Breed/(?P<pk>\d+)/$', views.BreedDelete.as_view(), name='BreedDelete'),
    url(r'^delete/AnimalSubGroup/(?P<pk>\d+)/$', views.AnimalSubGroupDelete.as_view(), name='AnimalSubGroupDelete'),
    url(r'^delete/Origin/(?P<pk>\d+)/$', views.OriginDelete.as_view(), name='OriginDelete'),
    url(r'^delete/Animal/(?P<pk>\d+)/$', views.AnimalDelete.as_view(), name='AnimalDelete'),
    url(r'^delete/Reason/(?P<pk>\d+)/$', views.ReasonDelete.as_view(), name='ReasonDelete'),
    url(r'^delete/Vet/(?P<pk>\d+)/$', views.VetDelete.as_view(), name='VetDelete'),
    url(r'^delete/Medication/(?P<pk>\d+)/$', views.MedicationDelete.as_view(), name='MedicationDelete'),
    url(r'^delete/MedsGiven/(?P<pk>\d+)/$', views.MedsGivenDelete.as_view(), name='MedsGivenDelete'),
    url(r'^delete/EggLog/(?P<pk>\d+)/$', views.EggLogDelete.as_view(), name='EggLogDelete'),
    url(r'^delete/Wormer/(?P<pk>\d+)/$', views.WormerDelete.as_view(), name='WormerDelete'),
    url(r'^delete/SheepCare/(?P<pk>\d+)/$', views.SheepCareDelete.as_view(), name='SheepCareDelete'),
    url(r'^delete/Forage/(?P<pk>\d+)/$', views.ForageDelete.as_view(), name='ForageDelete'),
    url(r'^delete/Paddock/(?P<pk>\d+)/$', views.PaddockDelete.as_view(), name='PaddockDelete'),
    url(r'^delete/Note/(?P<pk>\d+)/$', views.NoteDelete.as_view(), name='NoteDelete'),
    url(r'^delete/Sale/(?P<pk>\d+)/$', views.SaleDelete.as_view(), name='SaleDelete'),
    url(r'^delete/SlayHouse/(?P<pk>\d+)/$', views.SlayHouseDelete.as_view(), name='SlayHouseDelete'),
    url(r'^delete/Slaughter/(?P<pk>\d+)/$', views.SlaughterDelete.as_view(), name='SlaughterDelete'),
    url(r'^delete/OtherDest/(?P<pk>\d+)/$', views.OtherDestDelete.as_view(), name='OtherDestDelete'),
    url(r'^delete/OtherReason/(?P<pk>\d+)/$', views.OtherReasonDelete.as_view(), name='OtherReasonDelete'),

farmdb/models/farm.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.utils import timezone

class Farm(models.Model):
    name = models.CharField(max_length=100, verbose_name='Farm name')
    address = models.CharField(max_length=150, verbose_name='Farm address')
    active = models.BooleanField(default=True, verbose_name='Farm active')
    date_of_creation = models.DateField(auto_created=timezone.now, verbose_name='Date of record creation')

    def __str__(self):
        return self.name


class FarmAdmin(admin.ModelAdmin):
    list_display = ('name', 'address', 'active', 'date_of_creation')
    search_fields = ('name', 'address')
    list_filter = ['active']
    date_hierarchy = 'date_of_creation'
    ordering = ('-date_of_creation',)


class Farmer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,default=None,null=True)
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10)
    active = models.BooleanField(default=False, verbose_name='Farmer active')
    reg_date = models.DateField(auto_created=timezone.now, verbose_name='Date of registration for farmer')

    def __str__(self):
        return self.user.last_name + ', ' + self.user.first_name


class FarmerAdmin(admin.ModelAdmin):
    list_display = ('user', 'farm', 'gender', 'active', 'reg_date')
    search_fields = ['farm']
    list_filter = ['active']
    date_hierarchy = 'reg_date'
    ordering = ('-reg_date', 'user__last_name', 'user__first_name')

farmdb/models/task.py
from django.db import models
from django.contrib import admin
from django.utils import timezone

from .farm import Farm
from .animalData import AnimalGroup,AnimalSubGroup

class Task(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    task = models.CharField(max_length=50)
    active = models.BooleanField(default=True)


class TaskMaster(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    comments = models.TextField()
    animalGroup = models.ForeignKey(AnimalGroup, on_delete=models.CASCADE)
    sub_group = models.ForeignKey(AnimalSubGroup, on_delete=models.CASCADE)
    workers = models.IntegerField()
    minutes = models.IntegerField()
    complete = models.BooleanField(default=False)


class TaskRecurring(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    start_date = models.DateField()
    comments = models.TextField()
    animalGroup = models.ForeignKey(AnimalGroup, on_delete=models.CASCADE)
    sub_group = models.ForeignKey(AnimalSubGroup, on_delete=models.CASCADE)
    workers = models.IntegerField()
    minutes = models.IntegerField()
    recur = models.CharField(max_length=15)

farmdb/forms.py
from .models import *
from django import forms
from django.contrib.auth.models import User



class FarmerForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','password','email']

class AnimalGroupForm(forms.ModelForm):

    class Meta:
        model = AnimalGroup
        fields = ['farm', 'animalGroup','active']

farmdb/templates/farmdb/listView/animal_list.html
{% extends "farmdb/base.html" %}
{% load tz %}

{% block body %}
<h1><center><strong>Animal</strong></center></h1>
{% if animal_list %}
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Farm</th>
            <th>AnimalID</th>
            <th>Gender</th>
            <th>Birth Date</th>
            <th>Mother</th>
            <th>Father</th>
            <th>Name</th>
            <th>Markings</th>
            <th>Photo</th>
            <th>Alive</th>
            <th>Comments</th>
            <th>Animal Group</th>
            <th>Breed</th>
            <th>Animal Sub Group</th>
            <th>Origin</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for al in animal_list %}
        <tr>
            <td>{{ al.farm }}</td>
            <td>{{ al.animalId }}</td>
            <td>{{ al.gender }}</td>
            <td>{{ al.birthDate }}</td>
            <td>{{ al.mother }}</td>
            <td>{{ al.father }}</td>
            <td>{{ al.name }}</td>
            <td>{{ al.markings }}</td>
            <td>{{ al.filename }}</td>
            <td>{{ al.alive }}</td>
            <td>{{ al.comments }}</td>
            <td>{{ al.animalGroup }}</td>
            <td>{{ al.breed }}</td>
            <td>{{ al.animalSubGroup }}</td>
            <td>{{ al.origin }}</td>
            <td> <a href="{% url 'farmdb:AnimalUpdate' pk=al.pk%}" class="btn btn-info" role="button">Edit</a></td>
            <td> <a href="{% url 'farmdb:AnimalDelete' pk=al.pk%}" class="btn btn-danger" role="button">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h2><center>You haven't added something in this category. Please added something for me to store.</center></h2>
{% endif %}
{% endblock %}

farmdb/templates/farmdb/listView/eggLog_list.html
{% extends "farmdb/base.html" %}
{% load tz %}

{% block body %}
<h1>
    <center><strong>EggLog</strong></center>
</h1>
{% if egglog_list %}
<form name="date" method="get">
    {% csrf_token %}
    <input id="from" type="date" name="From">
    <input id="to" type="date" name="To">
    <input class="btn btn-success" type="submit" value="Submit">
</form>
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Farm</th>
            <th>Collection Date</th>
            <th>Number</th>
            <th>Comments</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for el in egglog_list %}
        <tr>
            <td>{{ el.farm }}</td>
            <td>{{ el.collection_date }}</td>
            <td>{{ el.number }}</td>
            <td>{{ el.comments }}</td>
            <td><a href="{% url 'farmdb:EggLogUpdate' pk=el.pk%}" class="btn btn-info" role="button">Edit</a></td>
            <td><a href="{% url 'farmdb:EggLogDelete' pk=el.pk%}" class="btn btn-danger" role="button">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h2>
    <center>You haven't added something in this category. Please added something for me to store.</center>
</h2>
{% endif %}
{% endblock %}

farmdb/templates/farmdb/listView/forage_list.html
{% extends "farmdb/base.html" %}
{% load tz %}

{% block body %}
<h1><center><strong>Forage</strong></center></h1>
{% if forage_list %}
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Farm</th>
            <th>Forage</th>
            <th>Density</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for fr in forage_list %}
        <tr>
            <td>{{ fr.farm }}</td>
            <td>{{ fr.forage }}</td>
            <td>{{ fr.density }}</td>
            <td> <a href="{% url 'farmdb:ForageUpdate' pk=fr.pk%}" class="btn btn-info" role="button">Edit</a></td>
        <td> <a href="{% url 'farmdb:ForageDelete' pk=fr.pk%}" class="btn btn-danger" role="button">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h2><center>You haven't added something in this category. Please added something for me to store.</center></h2>
{% endif %}
{% endblock %}

farmdb/templates/farmdb/listView/medsGiven_list.html
{% extends "farmdb/base.html" %}
{% load tz %}

{% block body %}
<h1><center><strong>MedsGiven</strong></center></h1>
{% if medsgiven_list %}
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Farm</th>
            <th>Medication</th>
            <th>Units</th>
            <th>Units Given</th>
            <th>Vet ID</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for mg in medsgiven_list %}
        <tr>
            <td>{{ mg.farm }}</td>
            <td>{{ mg.medication }}</td>
            <td>{{ mg.units }}</td>
            <td>{{ mg.unitsGiven }}</td>
            <td>{{ mg.vetId }}</td>
            <td> <a href="{% url 'farmdb:MedsGivenUpdate' pk=mg.pk%}" class="btn btn-info" role="button">Edit</a></td>
        <td> <a href="{% url 'farmdb:MedsGivenDelete' pk=mg.pk%}" class="btn btn-danger" role="button">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h2><center>You haven't added something in this category. Please added something for me to store.</center></h2>
{% endif %}
{% endblock %}

farmdb/templates/farmdb/listView/note_list.html
{% extends "farmdb/base.html" %}
{% load tz %}

{% block body %}
<h1><center><strong>Note</strong></center></h1>
{% if note_list %}
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Farm</th>
            <th>Note Date</th>
            <th>Note</th>
            <th>Files</th>
            <th>Created by</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for nt in note_list %}
        <tr>
            <td>{{ nt.farm }}</td>
            <td>{{ nt.noteDate }}</td>
            <td>{{ nt.note }}</td>
            <td>{{ nt.filename }}</td>
            <td>{{ nt.created_by }}</td>
            <td> <a href="{% url 'farmdb:MedsGivenUpdate' pk=nt.pk%}" class="btn btn-info" role="button">Edit</a></td>
        <td> <a href="{% url 'farmdb:NoteCreate' pk=nt.pk%}" class="btn btn-danger" role="button">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h2><center>You haven't added something in this category. Please added something for me to store.</center></h2>
{% endif %}
{% endblock %}

farmdb/templates/farmdb/listView/otherDest_list.html
{% extends "farmdb/base.html" %}
{% load tz %}

{% block body %}
<h1><center><strong>OtherDest</strong></center></h1>
{% if otherdest_list %}
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Farm</th>
            <th>Other Dest</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for od in otherdest_list %}
        <tr>
            <td>{{ od.farm }}</td>
            <td>{{ od.dest }}</td>
            <td> <a href="{% url 'farmdb:OtherDestUpdate' pk=od.pk%}" class="btn btn-info" role="button">Edit</a></td>
        <td> <a href="{% url 'farmdb:OtherDestDelete' pk=od.pk%}" class="btn btn-danger" role="button">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h2><center>You haven't added something in this category. Please added something for me to store.</center></h2>
{% endif %}
{% endblock %}

farmdb/templates/farmdb/listView/sale_list.html
{% extends "farmdb/base.html" %}
{% load tz %}

{% block body %}
<h1><center><strong>Sale</strong></center></h1>
{% if sale_list %}
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Farm</th>
            <th>Animal</th>
            <th>Sale Tag</th>
            <th>Destination</th>
            <th>Weight</th>
            <th>Estimated</th>
            <th>Price/Lb</th>
            <th>Fees</th>
            <th>Comments</th>
            <th>Sale Date</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for sl in sale_list %}
        <tr>
            <td>{{ sl.farm }}</td>
            <td>{{ sl.animal }}</td>
            <td>{{ sl.saleTag }}</td>
            <td>{{ sl.destination }}</td>
            <td>{{ sl.weight }}</td>
            <td>{{ sl.estimated }}</td>
            <td>{{ sl.priceLb }}</td>
            <td>{{ sl.fees }}</td>
            <td>{{ sl.comments }}</td>
            <td>{{ sl.saleDate }}</td>
            <td> <a href="{% url 'farmdb:SaleUpdate' pk=sl.pk%}" class="btn btn-info" role="button">Edit</a></td>
        <td> <a href="{% url 'farmdb:SaleDelete' pk=sl.pk%}" class="btn btn-danger" role="button">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h2><center>You haven't added something in this category. Please added something for me to store.</center></h2>
{% endif %}
{% endblock %}

farmdb/templates/farmdb/listView/slaughter_list.html
{% extends "farmdb/base.html" %}
{% load tz %}

{% block body %}
<h1><center><strong>Slaughter</strong></center></h1>
{% if slaughter_list %}
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th>Farm</th>
            <th>Animal</th>
            <th>Sale Tag</th>
            <th>Slay House</th>
            <th>Hauler</th>
            <th>Haul Equipment</th>
            <th>Slay Date</th>
            <th>Weight</th>
            <th>Estimated Price</th>
            <th>Fees</th>
            <th>Comments</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for sl in slaughter_list %}
        <tr>
            <td>{{ sl.farm }}</td>
            <td>{{ sl.animal }}</td>
            <td>{{ sl.saleTag }}</td>
            <td>{{ sl.slayHouse }}</td>
            <td>{{ sl.hauler }}</td>
            <td>{{ sl.haulEquip }}</td>
            <td>{{ sl.slayDate }}</td>
            <td>{{ sl.weight }}</td>
            <td>{{ sl.estimated }}</td>
            <td>{{ sl.fees }}</td>
            <td>{{ sl.comments }}</td>
            <td> <a href="{% url 'farmdb:AnimalGroupUpdate' pk=sl.pk%}" class="btn btn-info" role="button">Edit</a></td>
        <td> <a href="{% url 'farmdb:SlaughterDelete' pk=sl.pk%}" class="btn btn-danger" role="button">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h2><center>You haven't added something in this category. Please added something for me to store.</center></h2>
{% endif %}
{% endblock %}