farmdata2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('farmdb.urls',namespace='farmdb')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmdb/urls.py
from django.conf.urls import url, include
from . import views



app_name = 'farmdb'

urlpatterns = [
    url(r'^login/', views.login_user, name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^logout', views.logout_user, name='logout'),

    # CreateViews
    url(r'^create/AnimalGroup$', views.AnimalGroupCreateView.as_view(), name="AnimalGroupCreate"),
    url(r'^create/Breed$', views.BreedCreateView.as_view(), name="BreedCreate"),
    url(r'^create/AnimalSubGroup$', views.AnimalSubGroupCreateView.as_view(), name="AnimalSubGroupCreate"),
    url(r'^create/Origin$', views.OriginCreateView.as_view(), name="OriginCreate"),
    url(r'^create/Animal$', views.AnimalCreateView.as_view(), name="AnimalCreate"),
    url(r'^create/Reason$', views.ReasonCreateView.as_view(), name="ReasonCreate"),
    url(r'^create/Vet$', views.VetCreateView.as_view(), name="VetCreate"),
    url(r'^create/Medication$', views.MedicationCreateView.as_view(), name="MedicationCreate"),
    url(r'^create/MedsGiven$', views.MedsGivenCreateView.as_view(), name="MedsGivenCreate"),
    url(r'^create/EggLog$', views.EggLogCreateView.as_view(), name="EggLogCreate"),
    url(r'^create/Wormer$', views.WormerCreateView.as_view(), name="WormerCreate"),
    url(r'^create/SheepCare$', views.SheepCareCreateView.as_view(), name="SheepCareCreate"),
    url(r'^create/Forage$', views.ForageCreateView.as_view(), name="ForageCreate"),
    url(r'^create/Paddock$', views.PaddockCreateView.as_view(), name="PaddockCreate"),
    url(r'^create/Note$', views.NoteCreateView.as_view(), name="NoteCreate"),
    url(r'^create/Sale$', views.SaleCreateView.as_view(), name="SaleCreate"),
    url(r'^create/SlayHouse$', views.SlayHouseCreateView.as_view(), name="SlayHouseCreate"),
    url(r'^create/Slaughter$', views.SlaughterCreateView.as_view(), name="SlaughterCreate"),
    url(r'^create/OtherDest$', views.OtherDestCreateView.as_view(), name="OtherDestCreate"),
    url(r'^create/OtherReason$', views.OtherReasonCreateView.as_view(), name="OtherReasonCreate"),
    url(r'^create/OtherRemove$', views.OtherRemoveCreateView.as_view(), name="OtherRemoveCreate"),
    url(r'^create/FeedType$', views.FeedTypeCreateView.as_view(), name="FeedTypeCreate"),
    url(r'^create/FeedUnit$', views.FeedUnitCreateView.as_view(), name="FeedUnitCreate"),
    url(r'^create/FeedSubtype$', views.FeedSubtypeCreateView.as_view(), name="FeedSubtypeCreate"),
    url(r'^create/Vendor$', views.VendorCreateView.as_view(), name="VendorCreate"),
    url(r'^create/Destination$', views.DestinationCreateView.as_view(), name="DestinationCreate"),
    url(r'^create/FeedPurchase$', views.FeedPurchaseCreateView.as_view(), name="FeedPurchaseCreate"),

    # List views
    url(r'^list/Animal$', views.AnimalListView.as_view(), name='AnimalList'),
    url(r'^list/Reason$', views.ReasonListView.as_view(), name='ReasonList'),
    url(r'^list/AnimalGroup$', views.AnimalGroupListView.as_view(), name='AnimalGroupList'),
    url(r'^list/Breed$', views.BreedListView.as_view(), name='BreedList'),
    url(r'^list/AnimalSubGroup$', views.AnimalSubGroupListView.as_view(), name='AnimalSubGroupList'),
    url(r'^list/Origin$', views.OriginListView.as_view(), name='OriginList'),
    url(r'^list/Animal$', views.AnimalListView.as_view(), name='AnimalList'),
    url(r'^list/Reason$', views.ReasonListView.as_view(), name='ReasonList'),
    url(r'^list/Vet$', views.VetListView.as_view(), name='VetList'),
    url(r'^list/Medication$', views.MedicationListView.as_view(), name='MedicationList'),
    url(r'^list/MedsGiven$', views.MedsGivenListView.as_view(), name='MedsGivenList'),
    url(r'^list/EggLog$', views.EggLogListView.as_view(), name='EggLogList'),
    url(r'^list/Wormer$', views.WormerListView.as_view(), name='WormerList'),
    url(r'^list/SheepCare$', views.SheepCareListView.as_view(), name='SheepCareList'),
    url(r'^list/Forage$', views.ForageListView.as_view(), name='ForageList'),
    url(r'^list/Paddock$', views.PaddockListView.as_view(), name='PaddockList'),
    url(r'^list/Note$', views.NoteListView.as_view(), name='NoteList'),
    url(r'^list/Sale$', views.SaleListView.as_view(), name='SaleList'),
    url(r'^list/SlayHouse$', views.SlayHouseListView.as_view(), name='SlayHouseList'),
    url(r'^list/Slaughter$', views.SlaughterListView.as_view(), name='SlaughterList'),
    url(r'^list/OtherDest$', views.OtherDestListView.as_view(), name='OtherDestList'),
    url(r'^list/OtherReason$', views.OtherReasonListView.as_view(), name='OtherReasonList'),
    url(r'^list/OtherRemove$', views.OtherRemoveListView.as_view(), name='OtherRemoveList'),
    url(r'^list/FeedType$', views.FeedTypeListView.as_view(), name='FeedTypeList'),
    url(r'^list/FeedUnit$', views.FeedUnitListView.as_view(), name='FeedUnitList'),
    url(r'^list/FeedSubtype$', views.FeedSubtypeListView.as_view(), name='FeedSubtypeList'),
    url(r'^list/Vendor$', views.VendorListView.as_view(), name='VendorList'),
    url(r'^list/FeedPurchase$', views.FeedPurchaseListView.as_view(), name='FeedPurchaseList'),
    url(r'^list/Destination$', views.DestinationListView.as_view(), name='DestinationList'),

    # DetailViews

    # UpdateViews
    url(r'^update/AnimalGroup/(?P<pk>\d+)/$', views.AnimalGroupUpdateView.as_view(), name='AnimalGroupUpdate'),
    url(r'^update/Breed/(?P<pk>\d+)/$', views.BreedUpdateView.as_view(), name='BreedUpdate'),
    url(r'^update/AnimalSubGroup/(?P<pk>\d+)/$', views.AnimalSubGroupUpdateView.as_view(), name='AnimalSubGroupUpdate'),
    url(r'^update/Origin/(?P<pk>\d+)/$', views.OriginUpdateView.as_view(), name='OriginUpdate'),
    url(r'^update/Animal/(?P<pk>\d+)/$', views.AnimalUpdateView.as_view(), name='AnimalUpdate'),
    url(r'^update/Reason/(?P<pk>\d+)/$', views.ReasonUpdateView.as_view(), name='ReasonUpdate'),
    url(r'^update/Vet/(?P<pk>\d+)/$', views.VetUpdateView.as_view(), name='VetUpdate'),
    url(r'^update/Medication/(?P<pk>\d+)/$', views.MedicationUpdateView.as_view(), name='MedicationUpdate'),
    url(r'^update/MedsGiven/(?P<pk>\d+)/$', views.MedsGivenUpdateView.as_view(), name='MedsGivenUpdate'),
    url(r'^update/EggLog/(?P<pk>\d+)/$', views.EggLogUpdateView.as_view(), name='EggLogUpdate'),
    url(r'^update/Wormer/(?P<pk>\d+)/$', views.WormerUpdateView.as_view(), name='WormerUpdate'),
    url(r'^update/SheepCare/(?P<pk>\d+)/$', views.SheepCareUpdateView.as_view(), name='SheepCareUpdate'),
    url(r'^update/Forage/(?P<pk>\d+)/$', views.ForageUpdateView.as_view(), name='ForageUpdate'),
    url(r'^update/Paddock/(?P<pk>\d+)/$', views.PaddockUpdateView.as_view(), name='PaddockUpdate'),
    url(r'^update/Note/(?P<pk>\d+)/$', views.NoteUpdateView.as_view(), name='NoteUpdate'),
    url(r'^update/Destination/(?P<pk>\d+)/$', views.DestinationUpdateView.as_view(), name='DestinationUpdate'),
    url(r'^update/Sale/(?P<pk>\d+)/$', views.SaleUpdateView.as_view(), name='SaleUpdate'),
    url(r'^update/SlayHouse/(?P<pk>\d+)/$', views.SlayHouseUpdateView.as_view(), name='SlayHouseUpdate'),
    url(r'^update/Slaughter/(?P<pk>\d+)/$', views.SlaughterUpdateView.as_view(), name='SlaughterUpdate'),
    url(r'^update/OtherDest/(?P<pk>\d+)/$', views.OtherDestUpdateView.as_view(), name='OtherDestUpdate'),
    url(r'^update/OtherReason/(?P<pk>\d+)/$', views.OtherReasonUpdateView.as_view(), name='OtherReasonUpdate'),
    url(r'^update/OtherRemove/(?P<pk>\d+)/$', views.OtherRemoveUpdateView.as_view(), name='OtherRemoveUpdate'),
    url(r'^update/FeedType/(?P<pk>\d+)/$', views.FeedTypeUpdateView.as_view(), name='FeedTypeUpdate'),
    url(r'^update/FeedSubtype/(?P<pk>\d+)/$', views.FeedSubtypeUpdateView.as_view(), name='FeedSubtypeUpdate'),
    url(r'^update/FeedUnit/(?P<pk>\d+)/$', views.FeedUnitUpdateView.as_view(), name='FeedUnitUpdate'),
    url(r'^update/Vendor/(?P<pk>\d+)/$', views.VendorUpdateView.as_view(), name='VendorUpdate'),
    url(r'^update/FeedPurchase/(?P<pk>\d+)/$', views.FeedPurchaseUpdateView.as_view(), name='FeedPurchaseUpdate'),

    # DeleteViews
    url(r'^delete/AnimalGroup/(?P<pk>\d+)/$', views.AnimalGroupDelete.as_view(), name='AnimalGroupDelete'),
    url(r'^delete/Breed/(?P<pk>\d+)/$', views.BreedDelete.as_view(), name='BreedDelete'),
    url(r'^delete/AnimalSubGroup/(?P<pk>\d+)/$', views.AnimalSubGroupDelete.as_view(), name='AnimalSubGroupDelete'),
    url(r'^delete/Origin/(?P<pk>\d+)/$', views.OriginDelete.as_view(), name='OriginDelete'),
    url(r'^delete/Animal/(?P<pk>\d+)/$', views.AnimalDelete.as_view(), name='AnimalDelete'),
    url(r'^delete/Reason/(?P<pk>\d+)/$', views.ReasonDelete.as_view(), name='ReasonDelete'),
    url(r'^delete/Vet/(?P<pk>\d+)/$', views.VetDelete.as_view(), name='VetDelete'),
    url(r'^delete/Medication/(?P<pk>\d+)/$', views.MedicationDelete.as_view(), name='MedicationDelete'),
    url(r'^delete/MedsGiven/(?P<pk>\d+)/$', views.MedsGivenDelete.as_view(), name='MedsGivenDelete'),
    url(r'^delete/EggLog/(?P<pk>\d+)/$', views.EggLogDelete.as_view(), name='EggLogDelete'),
    url(r'^delete/Wormer/(?P<pk>\d+)/$', views.WormerDelete.as_view(), name='WormerDelete'),
    url(r'^delete/SheepCare/(?P<pk>\d+)/$', views.SheepCareDelete.as_view(), name='SheepCareDelete'),
    url(r'^delete/Forage/(?P<pk>\d+)/$', views.ForageDelete.as_view(), name='ForageDelete'),
    url(r'^delete/Paddock/(?P<pk>\d+)/$', views.PaddockDelete.as_view(), name='PaddockDelete'),
    url(r'^delete/Note/(?P<pk>\d+)/$', views.NoteDelete.as_view(), name='NoteDelete'),
    url(r'^delete/Sale/(?P<pk>\d+)/$', views.SaleDelete.as_view(), name='SaleDelete'),
    url(r'^delete/SlayHouse/(?P<pk>\d+)/$', views.SlayHouseDelete.as_view(), name='SlayHouseDelete'),
    url(r'^delete/Slaughter/(?P<pk>\d+)/$', views.SlaughterDelete.as_view(), name='SlaughterDelete'),
    url(r'^delete/OtherDest/(?P<pk>\d+)/$', views.OtherDestDelete.as_view(), name='OtherDestDelete'),
    url(r'^delete/OtherReason/(?P<pk>\d+)/$', views.OtherReasonDelete.as_view(), name='OtherReasonDelete'),

farmdb/models/farm.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.utils import timezone

class Farm(models.Model):
    name = models.CharField(max_length=100, verbose_name='Farm name')
    address = models.CharField(max_length=150, verbose_name='Farm address')
    active = models.BooleanField(default=True, verbose_name='Farm active')
    date_of_creation = models.DateField(auto_created=timezone.now, verbose_name='Date of record creation')

    def __str__(self):
        return self.name


class FarmAdmin(admin.ModelAdmin):
    list_display = ('name', 'address', 'active', 'date_of_creation')
    search_fields = ('name', 'address')
    list_filter = ['active']
    date_hierarchy = 'date_of_creation'
    ordering = ('-date_of_creation',)


class Farmer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,default=None,null=True)
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10)
    active = models.BooleanField(default=False, verbose_name='Farmer active')
    reg_date = models.DateField(auto_created=timezone.now, verbose_name='Date of registration for farmer')

    def __str__(self):
        return self.user.last_name + ', ' + self.user.first_name


class FarmerAdmin(admin.ModelAdmin):
    list_display = ('user', 'farm', 'gender', 'active', 'reg_date')
    search_fields = ['farm']
    list_filter = ['active']
    date_hierarchy = 'reg_date'
    ordering = ('-reg_date', 'user__last_name', 'user__first_name')

farmdb/models/task.py
from django.db import models
from django.contrib import admin
from django.utils import timezone

from .farm import Farm
from .animalData import AnimalGroup,AnimalSubGroup

class Task(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    task = models.CharField(max_length=50)
    active = models.BooleanField(default=True)


class TaskMaster(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    comments = models.TextField()
    animalGroup = models.ForeignKey(AnimalGroup, on_delete=models.CASCADE)
    sub_group = models.ForeignKey(AnimalSubGroup, on_delete=models.CASCADE)
    workers = models.IntegerField()
    minutes = models.IntegerField()
    complete = models.BooleanField(default=False)


class TaskRecurring(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    start_date = models.DateField()
    comments = models.TextField()
    animalGroup = models.ForeignKey(AnimalGroup, on_delete=models.CASCADE)
    sub_group = models.ForeignKey(AnimalSubGroup, on_delete=models.CASCADE)
    workers = models.IntegerField()
    minutes = models.IntegerField()
    recur = models.CharField(max_length=15)

farmdb/forms.py
from .models import *
from django import forms
from django.contrib.auth.models import User



class FarmerForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','password','email']

class AnimalGroupForm(forms.ModelForm):

    class Meta:
        model = AnimalGroup
        fields = ['farm', 'animalGroup','active']

farmdb/templates/farmdb/base.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}AnimalDB{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'farmdb/assets/css/styles.min.css'%}">
    <link rel="stylesheet" href="{% static 'farmdb/assets/css/styles.css'%}">
</head>

<body style="font-family:Comic Sans MS, Comic Sans, cursive;">
    <div>
        <nav class="navbar navbar-default navbar-inverse" id="navbase">
            <div class="container">
                <div class="navbar-header"><a class="navbar-brand navbar-link" href="#" style="font-family:'Kaushan Script',cursive;color:white;">FarmData 2.0 </a>
                    <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                </div>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="nav navbar-nav navbar-right" style="margin:0px;">
                        <li class="active" role="presentation"><a href="#">Animal DB</a></li>
                        <li role="presentation"><a href="#">FAQ </a></li>
                        <li role="presentation"><a href="#">Contact Us</a></li>
                        <li role="presentation"><a href="{% url 'farmdb:logout' %}"><i class="glyphicon glyphicon-log-out"></i></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div id='bodyWrapper' class="container">


        {% block body%}


        {% endblock %}


    </div>
    <div class="footer-basic inverse" style="/*background:#282d32;*/">
        <footer>
            <div class="social"><a href="#" style="color:white;"><i class="icon ion-social-facebook" style="color:white;"></i></a><a href="#"><i class="icon ion-email" style="color:white;"></i></a><a href="#"><i class="icon ion-social-github" style="color:white;"></i></a></div>
            <p
            class="copyright" style="text-align:center;">This contents and database schemas of this site are licensed under GPL v3.0</p>
                <p class="copyright">FarmDev © 2017</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>

farmdb/templates/farmdb/delete_confirm.html
{% extends 'farmdb/base.html' %}
{% block body %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
{% endblock %}

farmdb/templates/farmdb/index.html
{% extends 'farmdb/base.html' %}
{% block body %}
    <!--<h1>-->
        <!--<center>Create</center>-->
    <!--</h1>-->
    <!--<div>-->
        <!--<div class="container select_item">-->
            <!--<div class="row select_item">-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:AnimalGroupCreate' %}">AnimalGroup</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:BreedCreate' %}">Breed</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:AnimalSubGroupCreate' %}">AnimalSubGroup</a>-->
                <!--</div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:OriginCreate' %}">Origin</a></div>-->
            <!--</div>-->
            <!--<div class="row select_item">-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:AnimalCreate' %}">Animal</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:ReasonCreate' %}">Reason</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:VetCreate' %}">Vet</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:MedicationCreate' %}">Medication</a></div>-->
            <!--</div>-->
            <!--<div class="row select_item">-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:MedsGivenCreate' %}">MedsGiven</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:EggLogCreate' %}">EggLog</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:WormerCreate' %}">Wormer</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:SheepCareCreate' %}">SheepCare</a></div>-->
            <!--</div>-->
            <!--<div class="row select_item">-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:ForageCreate' %}">Forage</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:PaddockCreate' %}">Paddock</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:NoteCreate' %}">Note</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:DestinationCreate' %}">Destination</a></div>-->
            <!--</div>-->
            <!--<div class="row select_item">-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:SaleCreate' %}">Sale</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:SlayHouseCreate' %}">SlayHouse</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:SlaughterCreate' %}">Slaughter</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:OtherDestCreate' %}">OtherDest</a></div>-->
            <!--</div>-->
            <!--<div class="row select_item">-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:OtherReasonCreate' %}">OtherReason</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:OtherRemoveCreate' %}">OtherRemove</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:FeedTypeCreate' %}">FeedType</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:FeedSubtypeCreate' %}">FeedSubtype</a></div>-->
            <!--</div>-->
            <!--<div class="row select_item">-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:FeedUnitCreate' %}">FeedUnit</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:VendorCreate' %}">Vendor</a></div>-->
                <!--<div class="col-md-3 select_item"><a href="{% url 'farmdb:FeedPurchaseCreate' %}">FeedPurchase</a></div>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
    <h1>
        <center>Category</center>
    </h1>
    <div>
        <div class="container select_item">
            <div class="row select_item">
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:AnimalGroupList' %}">AnimalGroup</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:BreedList' %}">Breed</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:AnimalSubGroupList' %}">AnimalSubGroup</a>
                </div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:OriginList' %}">Origin</a></div>
            </div>
            <div class="row select_item">
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:AnimalList' %}">Animal</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:ReasonList' %}">Reason</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:VetList' %}">Vet</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:MedicationList' %}">Medication</a></div>
            </div>
            <div class="row select_item">
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:MedsGivenList' %}">MedsGiven</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:EggLogList' %}">EggLog</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:WormerList' %}">Wormer</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:SheepCareList' %}">SheepCare</a></div>
            </div>
            <div class="row select_item">
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:ForageList' %}">Forage</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:PaddockList' %}">Paddock</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:NoteList' %}">Note</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:DestinationList' %}">Destination</a></div>
            </div>
            <div class="row select_item">
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:SaleList' %}">Sale</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:SlayHouseList' %}">SlayHouse</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:SlaughterList' %}">Slaughter</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:OtherDestList' %}">OtherDest</a></div>
            </div>
            <div class="row select_item">
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:OtherReasonList' %}">OtherReason</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:OtherRemoveList' %}">OtherRemove</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:FeedTypeList' %}">FeedType</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:FeedSubtypeList' %}">FeedSubtype</a></div>
            </div>
            <div class="row select_item">
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:FeedUnitList' %}">FeedUnit</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:VendorList' %}">Vendor</a></div>
                <div class="col-md-3 select_item"><a href="{% url 'farmdb:FeedPurchaseList' %}">FeedPurchase</a></div>
                <div class="col-md-3 select_item">
                </div>
            </div>
        </div>


{% endblock %}